### ISSUE TITLE
Failed to Load in Forge 40.0.18 and 40.0.19

### ISSUE THREAD

**Issue by EldrinFal** [manmaed/cottenly#3]
### Cottonly version

0.10.1

### Minecraft Version

1.18.2

### Forge Version

40.0.19

### Do you have optifine installed?

Yes

### Describe the issue

Mod Failed to Load Error

### Steps to reproduce

1. Set version of Forge to 40.0.18 or 40.0.19
2. Run with latest mod ver 0.10.1
3.  Failed to Load error should appear after some load tim
[crash-2022-03-19_22.50.05-fml.txt](https://github.com/manmaed/cottonly/files/8310679/crash-2022-03-19_22.50.05-fml.txt)
e

### Expected behaviour

No error

### Information

- [X] I have provided as much information as possible

**Comment by manmaed** [comment]
Update to version cottonly 10.3
