### ISSUE TITLE
On the fabric version it's impossible to get seed with grass

### ISSUE THREAD

**Issue by delfar** [manmaed/cottenly#4]
### Cottonly version

0.12.1

### Minecraft Version

1.19.2

### Forge Version

fabric 0.14.9

### Do you have optifine installed?

No

### Describe the issue

The seed is only obtainable in creative mod if i give it to me but it's impossible to get one with grass, i only get normal seed.

### Steps to reproduce

launch minecraft with fabric and cottonly, break grass, you drop only normal seed

### Expected behaviour

drop cotton seed

### Information

- [X] I have provided as much information as possible

**Comment by manmaed** [comment]
It Drops for me in a non dev world you may have to break a few
