### ISSUE TITLE
Make the mod available to mod managers to download [Feature request]

### ISSUE THREAD

**Issue by otavio-silva** [manmaed/cottenly#5]
**Is your feature request related to a problem? Please describe.**
I can't download this mod through PolyMC mod manager

**Describe the solution you'd like**
I can't download because somewhere through the CurseForge API the mod is not tagged with the proper version

**Describe alternatives you've considered**
Tag the mod with it's version in CurseForge

**Additional context**
The mod manager can't find any version of the mod properly

**Comment by manmaed** [comment]
Hello, I do believe that all the tags are correct
![](https://ss.manmaed.net/1665614801.png)
