### ISSUE TITLE
[Bug] cotton seeds cant be consumed by the vanilla composter.

### ISSUE THREAD

**Issue by jjubenv** [manmaed/cottenly#7]
I'm currently using the "FTB Presents Direwolf20 1.21" pack and have small farm that I planted cotton to get string.  I get a lot of extra seeds that I can't do anything with, so I'd like to compost them, this is similar to other seeds in the game.

**Comment by manmaed** [comment]
It Should be

**Comment by manmaed** [comment]
Ok It Seems NeoForge Changed how its done

**Comment by manmaed** [comment]
Fixed in 16.3

**Comment by jjubenv** [comment]
Just downloaded 0.16.3 and replaced the 0.16.1 version in the pack.  It works!  Thanks for looking into this quickly!

**Comment by manmaed** [comment]
Just know JEI dosnt show the recipe anymore have reported to mezz https://github.com/mezz/JustEnoughItems/issues/3789
